[options]
admin_passwd = admin
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_maxconn = 64
data_dir = /var/lib/odoo
addons_path = /opt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
list_db = True
proxy_mode = False
workers = 0
max_cron_threads = 1
without_demo = all
log_level = info
