{
    "name": "TCSI Accounting",
    "summary": "Third Code Solutions Inc. accounting workspace",
    "version": "18.0.2.5.5",
    "category": "Accounting/Accounting",
    "author": "Third Code Solutions Inc.",
    "license": "AGPL-3",
    "website": "https://www.thirdcodesolutions.com",
    "depends": [
        "account",
        "account_payment",
        "spreadsheet_dashboard",
        "contacts",
        "auth_signup",
        "portal",
        "digest",
        "mail_bot",
        "hr_expense",
        "auditlog",
        "date_range",
        "report_xlsx",
        "report_xlsx_helper",
        "account_financial_report",
        "partner_statement",
        "account_statement_base",
        "account_reconcile_model_oca",
        "account_reconcile_oca",
        "account_statement_reconcile_status",
    ],
    "assets": {
        "web.assets_backend": [
            "thirdcode_accounting/static/src/scss/tcsi_brand.scss",
            "thirdcode_accounting/static/src/scss/tcsi_chat.scss",
            "thirdcode_accounting/static/src/js/tcsi_brand.js",
            "thirdcode_accounting/static/src/js/tcsi_error_branding.js",
            "thirdcode_accounting/static/src/js/tcsi_dashboard.js",
            "thirdcode_accounting/static/src/scss/tcsi_dashboard.scss",
            "thirdcode_accounting/static/src/scss/tcsi_routes.scss",
            "thirdcode_accounting/static/src/xml/tcsi_dashboard.xml",
        ],
        "web.assets_frontend": [
            "thirdcode_accounting/static/src/scss/tcsi_brand.scss",
        ],
    },
    "data": [
        "data/ir_sequence_data.xml",
        "data/ir_cron_data.xml",
        "data/branding_data.xml",
        "data/auditlog_rule_data.xml",
        "views/branding_templates.xml",
        "views/branding_communications.xml",
        "views/dashboard_views.xml",
        "security/thirdcode_groups.xml",
        "security/ir.model.access.csv",
        "views/res_company_views.xml",
        "views/account_journal_views.xml",
        "views/account_move_views.xml",
        "views/account_payment_views.xml",
        "views/payment_batch_views.xml",
        "views/recurring_journal_views.xml",
        "views/accounting_period_views.xml",
        "views/migration_views.xml",
        "views/recurring_invoice_views.xml",
        "views/report_sample_views.xml",
        "views/tax_profile_views.xml",
        "views/bank_reconciliation_views.xml",
        "views/year_end_close_views.xml",
        "views/financial_report_views.xml",
        "views/menu_views.xml",
        "report/thirdcode_reports.xml",
        "report/thirdcode_templates.xml",
    ],
    "installable": True,
    "application": True,
    "post_init_hook": "post_init_hook",
}
