"""Immutable evidence for privileged platform operations; no payload bodies."""
from odoo import _, api, fields, models
from odoo.exceptions import AccessError
from .platform_access import require_platform_owner


class PlatformEvent(models.Model):
    _name = "thirdcode.platform.event"
    _description = "Platform operation evidence"
    _order = "id desc"

    actor_id = fields.Many2one("res.users", required=True, ondelete="restrict")
    action = fields.Char(required=True, index=True)
    target = fields.Char(required=True)
    company_id = fields.Many2one("res.company", ondelete="restrict")

    @api.model_create_multi
    def create(self, values_list):
        raise AccessError(_("Operation evidence is generated by the system."))

    def write(self, values):
        raise AccessError(_("Operation evidence cannot be edited."))

    def unlink(self):
        raise AccessError(_("Operation evidence cannot be deleted."))

    @api.model
    def _record(self, action, target, company=None):
        require_platform_owner(self.env)
        return super(PlatformEvent, self.sudo()).create({
            "actor_id": self.env.uid, "action": str(action)[:80],
            "target": str(target)[:200], "company_id": company.id if company else False,
        })
